### ISSUE TITLE
J2V8&xxx.a

### ISSUE THREAD

**Issue by SparoJ** [leibniz55/J2V8ForArm64#1]
Hi, there,
I'd like to know where did you get the libv8_base.a xxx.a（static link library). I didn't find them under eclipsesource/J2V8 .

**Comment by devikkim** [comment]
Hi nice to meet to you 

Thank you for ask about my repository

The .a file to be made(build) myself in linux

There is the way about make .a file for v8 in my repository called “ComplieV8ForAndroid”

**Comment by SparoJ** [comment]
In the very beginning, i thought you build the .a library through the J2V8 library, when i looking further i get to know that the J2V8 doesn't seem to have that kind of ability.
I just want to make sure what i find out is true. 
Two weeks ago i was trying to build the v8 static library(.a) on my macOS but i failed, 
then i switch to the Linux Ubuntu through VMware on my MBP, the network sucks while i pull the resource from the google source sites , which i will try another time perhaps i will consult you in the future and thank you for replying me. ^ ^
